### PR TITLE
Anaconda notebook

### PR DESCRIPTION
**Pull request by Xaenalt**
Can we put this into a separate branch somewhere to track this feature?

## This introduces a breaking change

- [X] Yes
- [ ] No

This is the anaconda version of the notebook, depends on https://github.com/red-hat-data-services/s2i-python-anaconda-base as the base image

### CODE REVIEW

**Review by crobby — CHANGES_REQUESTED** [review]
Looks like we need at least a rebase here to resolve some things before this can be merged.

**Comment by crobby** [comment]
So...does this wind-up replacing the existing minimal notebook or does this one get added as an extra option in the dropdown once a customer has enabled anaconda?  Something else?

**Comment by vpavlin** [comment]
> So...does this wind-up replacing the existing minimal notebook or does this one get added as an extra option in the dropdown once a customer has enabled anaconda? Something else?

IIUC it is an additional image

**Comment by crobby** [comment]
> > So...does this wind-up replacing the existing minimal notebook or does this one get added as an extra option in the dropdown once a customer has enabled anaconda? Something else?
> 
> IIUC it is an additional image

Thanks.  Upon further review, I did indeed see the extra image in the dropdown after I enabled anaconda in my test instance.

**Comment by harshad16** [comment]
Hi @Xaenalt ,
This repository slightly deviates from the thoth-station/s2i-minimal-notebook.
I would recommend rebasing or make changes based on this repo.

As the anaconda based image would be separate.
It would useful to define the base image as well, as there was not conda install information added in the changes.

**Comment by Xaenalt** [comment]
So that's why I wanted to put it off in a separate branch, since it's likely impossible to make it work with the current way the repo is laid out. It's mainly just to get this out of my personal github and to an official one

**Comment by crobby** [comment]
> So that's why I wanted to put it off in a separate branch, since it's likely impossible to make it work with the current way the repo is laid out. It's mainly just to get this out of my personal github and to an official one

This PR is against master though.  Was the intent to send it to a branch?  Or should it just be in its own repo under RHDS?

**Comment by Xaenalt** [comment]
Yes, it should go under a branch

**Comment by crobby** [comment]
> Yes, it should go under a branch

I think you may need to re-open this PR (or maybe you can edit it) to get that to happen.

**Comment by Xaenalt** [comment]
Can you open up a branch for me to put it against? It doesn't let me do a PR against a non-existent branch

**Comment by crobby** [comment]
> Can you open up a branch for me to put it against? It doesn't let me do a PR against a non-existent branch

Is this really just another branch for this repo or should it be a totally separate repo?  Maybe I'm just lacking some understanding here, but my gut tells me that this should be another repo to reduce the chance for confusion. Thoughts @harshad16 ?

**Comment by harshad16** [comment]
> Is this really just another branch for this repo or should it be a totally separate repo? Maybe I'm just lacking some understanding here, but my gut tells me that this should be another repo to reduce the chance for confusion. Thoughts ?

I m also not fully sure. what I did for now in upstream is created a separate branch to see what all is to be done.
As we know it would be a different image in RHODS, maybe we can create a separate repo for this.
however we would need for information is what i feel, like what base image, what environment changes are to be made.
like to said we can create another repo to reduce chance of confusion.

**Comment by harshad16** [comment]
@Xaenalt move this pr to the https://github.com/red-hat-data-services/s2i-minimal-notebook-anaconda
lets work over there to get this fixed.

**Comment by Xaenalt** [comment]
I did in fact open that repo just to contain this set of changes

**Pull request closed without merging**
