### PR TITLE
Remove jupyterlab-requirements from Pipfile

### PR DESCRIPTION
**Pull request by tmckayus**
- [x] The commits are squashed in a cohesive manner and have meaningful messages.
- [x] For commits that came from upstream, `[UPSTREAM]` has been prepended to the commit message
- [x] JIRA link(s): https://issues.redhat.com/browse/RHODS-2161
- [x] The Jira story is acked
- [x] An entry has been added to the latest build document in [Build Announcements Folder](https://drive.google.com/drive/folders/1sgkK1WZgGo9CXsLizNe0GbAzVKuSKrZL).
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious)

### CODE REVIEW

**Comment by tmckayus** [comment]
This removes the "manage dependencies" link from the upper right notebook UI.
This change ultimately affects the pytorch and tensorflow notebooks in a rhods deployment, built on top of the minimal-gpu image built at runtime from this branch.

The minimal notebook available in the jhub launcher is built downstream from the master branch requirements*.txt files, which are already missing the jupyterhub-requirements dependency.

**Comment by harshad16** [comment]
The build-check can be seen from 
pr-build-run > build-run > logs

here is the reason:
```
+ jupyter labextension install @elyra/python-editor-extension@2.2.4 --no-build
An error occured.
ValueError: Please install nodejs >=12.0.0 before continuing. nodejs may be installed using conda or directly from the nodejs website.
See the log file for details:  /tmp/jupyterlab-debug-ji3ac8ns.log
subprocess exited with status 1
subprocess exited with status 1
error building at STEP "RUN /tmp/scripts/assemble": exit status 1'
+ exit_code=1
```

seems like the base image was changed, as it had nodejs 14 in it

**Review by crobby — COMMENTED** [review]
Looks right to me

**Pull request merged**
